apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-recommender-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bittush8789/E-Commerce-Recommendation-Engine.git
    targetRevision: cicd
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ml-serving
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
